### ISSUE TITLE
你好，如何连接数据库？

### ISSUE THREAD

**Issue by Hyhang669** [vencc/game#62]
方不方便给个联系方式，我想知道这个数据库怎么连接的。

**Comment by vencc** [comment]
如果想联机，就需要创建数据库，并创建 user 表，里面包含的字段顺序为 name,fileName,winNum,loseNum,tiedNum.
并修改 BaseDao 中的数据库变量，和 MyClient 中的 ip 地址，就可以进行联机对战了。

这里写的很详细了，若是不会使用数据库请自行google
